version: '3'

networks:
  inception:
volumes:
  data:
  wordpress:








services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    init : true
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build: 
      context : requirements/mariadb
      # args:
      # - MYSQL_USER
      # - MYSQL_PASSWORD
      # - MYSQL_DB
      # - MYSQL_HOST
      # - DB_ROOT_PASSWORD
    restart: unless-stopped
    volumes: 
      - data:/var/lib/mysql/
    env_file:
      - .env
    networks:
        - inception
    init: true
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    env_file:
      - .env
    restart: unless-stopped
    init : true
    ports:
      - "9000:9000"
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html