version: '3'

networks:
  inception:
volumes:
  data:
  wordpress:








services:
  nginx:
    build: requirements/nginx/

    restart: unless-stopped
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress/

    env_file:
      - .env
    restart: unless-stopped
    init : true
    ports:
      - "9000:9000"
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html


  mariadb:

    build: requirements/mariadb

    restart: unless-stopped
    volumes: 
      - data:/var/lib/mysql
    env_file:
      - .env
    networks:
        - inception